# Generated by Django 2.2.7 on 2019-12-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ta_app', '0001_initial'), ('ta_app', '0002_auto_20191110_1005'), ('ta_app', '0003_currentuser'), ('ta_app', '0004_auto_20191126_1340'), ('ta_app', '0005_auto_20191126_1341'), ('ta_app', '0006_auto_20191205_0104'), ('ta_app', '0007_auto_20191210_1313'), ('ta_app', '0008_break'), ('ta_app', '0009_break_userid'), ('ta_app', '0008_auto_20191217_1658'), ('ta_app', '0010_merge_20191217_1954'), ('ta_app', '0011_auto_20191218_2021'), ('ta_app', '0012_remove_course_day'), ('ta_app', '0013_course_day'), ('ta_app', '0014_auto_20191218_2140'), ('ta_app', '0015_auto_20191218_2207')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ta', models.IntegerField(blank=True, default=0, null=True)),
                ('instructor', models.IntegerField(blank=True, default=0, null=True)),
                ('coursetype', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('ON', 'Online'), ('GRD', 'Grading')], default='LEC', max_length=3)),
                ('lectureid', models.IntegerField(blank=True, default=0, null=True)),
                ('ta1', models.IntegerField(blank=True, default=0, null=True)),
                ('ta2', models.IntegerField(blank=True, default=0, null=True)),
                ('ta3', models.IntegerField(blank=True, default=0, null=True)),
                ('ta4', models.IntegerField(blank=True, default=0, null=True)),
                ('fri_flag', models.BooleanField(default=False)),
                ('mon_flag', models.BooleanField(default=False)),
                ('sat_flag', models.BooleanField(default=False)),
                ('thurs_flag', models.BooleanField(default=False)),
                ('tues_flag', models.BooleanField(default=False)),
                ('wed_flag', models.BooleanField(default=False)),
                ('day', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NewUser', max_length=50)),
                ('password', models.CharField(default='password', max_length=20)),
                ('name', models.CharField(default='NewName', max_length=50)),
                ('usertype', models.CharField(default='ta', max_length=10)),
                ('email', models.EmailField(default='newUser@email.com', max_length=50)),
                ('assignedInstructor', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(max_length=100)),
                ('userid', models.IntegerField(blank=True, default=0, null=True)),
                ('fri_flag', models.BooleanField(default=False)),
                ('mon_flag', models.BooleanField(default=False)),
                ('sat_flag', models.BooleanField(default=False)),
                ('thurs_flag', models.BooleanField(default=False)),
                ('tues_flag', models.BooleanField(default=False)),
                ('wed_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
