# Generated by Django 2.2.7 on 2019-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(max_length=100)),
                ('ta', models.CharField(max_length=100, null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NewUser', max_length=50)),
                ('password', models.CharField(default='password', max_length=20)),
                ('name', models.CharField(default='NewName', max_length=50)),
                ('usertype', models.CharField(default='grad', max_length=10)),
                ('email', models.EmailField(default='newUser@email.com', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Thingy',
        ),
    ]
