# Generated by Django 2.2.7 on 2019-12-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0001_squashed_0015_auto_20191218_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
    ]
