# Generated by Django 2.2.7 on 2019-11-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0003_currentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currentUser',
        ),
        migrations.AddField(
            model_name='myuser',
            name='assignedInstructor',
            field=models.IntegerField(default='1', max_length=50),
        ),
    ]
