# Generated by Django 2.2.7 on 2019-11-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0004_auto_20191126_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='assignedInstructor',
            field=models.IntegerField(default='1'),
        ),
    ]
