# Generated by Django 2.2.7 on 2019-12-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0007_auto_20191210_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursetype',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Lab'), ('ON', 'Online'), ('GRD', 'Grading')], default='LEC', max_length=3),
        ),
    ]
