# Generated by Django 2.2.7 on 2019-12-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0008_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='userid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
