# Generated by Django 2.2.7 on 2019-12-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0008_auto_20191217_1658'),
        ('ta_app', '0009_break_userid'),
    ]

    operations = [
    ]
