# Generated by Django 2.2.7 on 2019-12-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0010_merge_20191217_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='F',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='R',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='S',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='T',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='W',
            field=models.BooleanField(default=False),
        ),
    ]
