# Generated by Django 2.2.7 on 2019-12-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0011_auto_20191218_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
    ]
