# Generated by Django 2.2.7 on 2019-12-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0012_remove_course_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
