# Generated by Django 2.2.7 on 2019-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0013_course_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='F',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='break',
            name='M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='break',
            name='R',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='break',
            name='S',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='break',
            name='T',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='break',
            name='W',
            field=models.BooleanField(default=False),
        ),
    ]
