# Generated by Django 2.2.7 on 2019-12-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_app', '0014_auto_20191218_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='break',
            old_name='F',
            new_name='fri_flag',
        ),
        migrations.RenameField(
            model_name='break',
            old_name='M',
            new_name='mon_flag',
        ),
        migrations.RenameField(
            model_name='break',
            old_name='R',
            new_name='sat_flag',
        ),
        migrations.RenameField(
            model_name='break',
            old_name='S',
            new_name='thurs_flag',
        ),
        migrations.RenameField(
            model_name='break',
            old_name='T',
            new_name='tues_flag',
        ),
        migrations.RenameField(
            model_name='break',
            old_name='W',
            new_name='wed_flag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='F',
            new_name='fri_flag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='M',
            new_name='mon_flag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='R',
            new_name='sat_flag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='S',
            new_name='thurs_flag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='T',
            new_name='tues_flag',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='W',
            new_name='wed_flag',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.CharField(default='ta', max_length=10),
        ),
    ]
